gateway:
  image:
    repository: harhatilatonttu/llm-telegram-bot-gateway # CI_GATEWAY_REPO
    tag: "15"  # CI_GATEWAY_TAG
  port: 8000

bot:
  image:
    repository: harhatilatonttu/llm-telegram-bot-bot # CI_BOT_REPO
    tag: "15"  # CI_BOT_TAG